### basics

In [1]:
#sets and detect if a list elemts are unique
x = {5,2,6,7}
x.add('4')

x = [5,2,2,8,5,3,4,2]

if len(x) == len(set(x)):
    print(f"x: {x} are unique")
else:
    print(f"x: {x} they are not")
        
print('\n')
        
    
def fnc(x):
    return x+5

#map
list(map(fnc,x))

#Lambda
fnc = lambda x:x+10
fnc(3)

#map + lambda
list(map(lambda x:x**2, x))


#filter: filter based on bool value
list(filter(lambda x:x%2==0, x))


#return dict keys
x = {'k1': 1, 'k2': 2}
list(x.keys())
list(x.items())

#check element inside sequence

1 in list(x.values())

list(x.values())


#tuple unpacking
x = [(1,2),(3,4),(5,6)]
for (i) in x:
    print (i)
print('\n')
for (i,j) in x:
    print (i)

x: [5, 2, 2, 8, 5, 3, 4, 2] they are not


(1, 2)
(3, 4)
(5, 6)


1
3
5

### Numpy

In [2]:
#Numpy

import numpy as np
np.random.seed(101)
x = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(x)
arr


#Define range or array using arange
np.arange(5)

#Zeros
np.zeros((2,4),dtype = int)

# return evenly spaced array vectory of 10 elements from 1,2
np.linspace(1,2,10)


#random
np.random.rand(100) #uniform 0-1
np.random.randn(10) #std normal
np.random.randint(0,2,10) #discrete uniform


#reshape
arr = np.arange(30)
arr = arr.reshape(5,6)

#usefull methods
arr.min()
arr.max()
arr.argmax() #return index numpy int for max value


#when make a new array of an array we need to use .copy method to avoid point in same place
arr2 = arr.copy()
arr2 +=2


#array indexing
arr2[2] 
arr2[2][1]

#array specail indexing
arr2[2,1] #numpy allow to index a tuple
arr2[2:,0:2] #get certain section of slice of an array

#conditional selection
arr = np.random.randint(1,11,20)
arr = arr.reshape((5,4))
arr >= 3 #return an array of bool
arr[arr >= 3]

#array operations
arr + arr
arr + 5
np.sqrt(arr)
1

1

### Pandas

In [347]:
#Pandas Series
import pandas as pd

labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array(my_list)
d = {'a':10,'b':20,'c':30}

# make a series out of list/Tuple/ arr
ser1 = pd.Series(data = my_list)
ser1 = pd.Series([10,20,30])

ser2 = pd.Series(data = my_list,index = labels)
ser2 = pd.Series([10,20,30],['a','b','c'])

ser3 = pd.Series([0,1,1,0],['a','b','c','d'])

# make a series out of Dict
pd.Series(d)
pd.Series({'a':10,'b':20,'c':30})

#series basic indexing 
ser1[0] #call my index name
ser2['a'] #call my index name

#series operations done per ((index))
ser2 *ser3


#Data Frames

df = pd.DataFrame(data = np.arange(1,21).reshape((5,4)),index = ['A','B','C','D','E'], columns = ['W','X','Y','Z'])


#indexing a single column name ==> Series
df['X']

#indexing a list of columns name ==> DataFrame
df[['X','Z']]

#Creating new columns
df['h'] = [1,2,3,4,3]

#indexing rows
df.loc[['A','B']]
df.iloc[0:4]

df
df.loc['A':'C']
df.loc[['B','C','D'],['X','Y']]


#Drop (coloumns - index)
df.drop(columns = 'h', inplace = True)
df['h'] = [1,2,3,4,3]
df.drop('h',axis = 1, inplace = True)
df.drop(index = ['A'], inplace = False)

#condetional selection
df[df['W']>10][['W','Y']]
df[(df['W']>=9) & (df['Z']<15)]

df

#reset or change index
df.reset_index(drop = True, inplace = True)

newind = 'AA BB CC DD EE'.split()
df['newind'] = newind
df.set_index(keys = 'newind', inplace = False)
df.drop(columns = 'newind', inplace = True)


# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

np.random.seed(101)
df2 = pd.DataFrame(data = np.random.randn(6,2),index = hier_index, columns = ['A','B'])
df2[['A']].loc['G1'].loc[[1]]

#Change index names
df2.index.names = ['Group','Num']
df2


#CrossSection xs usful when want to get same Num in different Group level
df2.xs('G1')
df2.xs(key = 1,level = 'Num')


#deal with missing data------------

df6 = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,np.nan,3]},
                  index = range(3))

#drop row-column missing data
Na = 1
df6.dropna(axis = 0, inplace = False, thresh = len(df.columns)-Na)


#fill missing data

df6.fillna(value='FILL VALUE')
df6
for i in list(df6.columns):
    df6[i].fillna(value= df6[i].mean(), inplace = True)

#GROUP BY

data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

df3 = pd.DataFrame(data)
df3.groupby('Company').describe().transpose()




#Merging - Joining - Concatination


df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

#concat joining axes with same name (union)
pd.concat([df1,df2,df3])


#merging and joinning 2 tables based on common key
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

pd.merge(left,right,how='right',on='key')

#merging and joinning 2 tables based on multiple common keys
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

pd.merge(left, right, how='outer', on=['key1', 'key2'])

#joining (mering based on common indexes)

left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

left.join(right,how = 'left')



#usfull operations



#find unique values
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
list(df['col2'].unique())
df['col2'].nunique() 
df['col2'].value_counts()



#use apply to apply functions into df !!! 

df['col3'] = df['col3'].apply(len)

def test(x):
    return x*2
df['col2'] = df['col2'].apply(test)
df['col1'] = df['col1'].apply(lambda x:x+10) #similer to map-lambda combination said to be the most used item in pandas!!!
df

#sorting DataFrames
df.sort_values(['col2','col1'], ascending = (0,0)).reset_index(drop = True)



#pivot tables (same as multi grouping with unstacked data)

data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}
df = pd.DataFrame(data)
df.pivot_table(values = 'D',index = ['A','B'],columns = ['C'], aggfunc = 'sum')
#equal to 
df.groupby(['A','B','C']).sum().unstack()

#read from html
df = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

#### Booking Plan

In [176]:
#import Booking Plan
import pandas as pd
booking_plan = pd.read_excel('my new dataframe.xlsx')

In [235]:
df2 = booking_plan[booking_plan['Status'] == 'C'].groupby(['GAC Yr','GAC Mth','Block'])[['Total Item Quantity']].sum()
df2.reset_index(['GAC Yr','GAC Mth'])

df3 = df2.unstack().fillna(value = 0)
df3.reset_index(inplace = True)
df3['Total Item Quantity'] = df3['Total Item Quantity'].astype('int')
df3.head(6)

      GAC Yr GAC Mth Total Item Quantity
Block                                  0       A       B
0       2022       1                   0  523305  414437
1       2022       2                   0  574367  395564
2       2022       3                   0  475723  547956
3       2022       4                   0  430485  501766
4       2022       5                   0  335462  299205
5       2022       6                   0  690323  682865